### ISSUE TITLE
Create unidirectional & bidirectional motor structs

### ISSUE THREAD

**Issue by rudranshkumar** [graysonk546/enph-253-2021#14]
**Description:**

Two flavors of DC motors, 1D and 2D, will be abstracted as structs so that the motors' parameters can be accessed from the purpose-built containers. 

**Tasks:**

- [x] Create 1D motor module
- [x] Created 2D motor module
- [x] Created 1D motor CLI module
- [x] Created 2D motor CLI module
